# API Keys for Stock Analysis Dashboard

# AI Model API Keys
OPENROUTER_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyBWS4ezPZnRASgXDVEs46ImaLOJOUStc0k"

# Stock Data Provider API Keys
ALPHA_VANTAGE_API_KEY = "ABCDEFGHIJKLMNOP"
TIINGO_API_KEY = "88d18ddc48bd2c6082a01a627da9ecde96deadcd"
FINNHUB_API_KEY = "cuvnje9r01qh55k60220cuvnje9r01qh55k6022g"

# Note: Replace these placeholder values with your actual API keys from:
# - DeepSeek: https://platform.deepseek.com
# - Google AI: https://makersuite.google.com
# - Alpha Vantage: https://www.alphavantage.co/support/#api-key
# - Tiingo: https://api.tiingo.com
# - FinnHub: https://finnhub.io
# - OpenRoauter: https://openrouter.ai/api/v1